### ISSUE TITLE
Request: Support namespaces

### ISSUE THREAD

**Issue by eddy147** [homanchou/elixir-xml-to-map#15]
Let;s say I have the following Xml:

`<jw315:Bericht xmlns:ijw="http://www.istandaarden.nl/ijw/3_0/basisschema/schema"
  xmlns:jw315="http://www.istandaarden.nl/ijw/3_0/jw315/schema">
  <jw315:Header>
    <jw315:BerichtCode>446</jw315:BerichtCode>
    <jw315:BerichtVersie>3</jw315:BerichtVersie>
    <jw315:BerichtSubversie>0</jw315:BerichtSubversie>
    <jw315:Afzender>22227338</jw315:Afzender>
    <jw315:Ontvanger>0344</jw315:Ontvanger>
    <jw315:BerichtIdentificatie>
      <ijw:Identificatie>MC008896A559</ijw:Identificatie>
      <ijw:Dagtekening>2021-01-19</ijw:Dagtekening>
    </jw315:BerichtIdentificatie>
    <jw315:XsdVersie>
      <ijw:BasisschemaXsdVersie>1.2.0</ijw:BasisschemaXsdVersie>
      <ijw:BerichtXsdVersie>1.0.2</ijw:BerichtXsdVersie>
    </jw315:XsdVersie>
  </jw315:Header>
  <jw315:Client>
    <jw315:Bsn>999900006</jw315:Bsn>
    <jw315:Geboortedatum>
      <ijw:Datum>2021-01-01</ijw:Datum>
    </jw315:Geboortedatum>
    <jw315:Geslacht>1</jw315:Geslacht>
    <jw315:Naam>
      <ijw:Geslachtsnaam>
        <ijw:Achternaam>Vries</ijw:Achternaam>
      </ijw:Geslachtsnaam>
      <ijw:Voorletters>P</ijw:Voorletters>
    </jw315:Naam>
    <jw315:GezagsdragerBekend>1</jw315:GezagsdragerBekend>
    <jw315:AangevraagdeProducten>
      <jw315:AangevraagdProduct>
        <jw315:ReferentieAanbieder>88efe721359587</jw315:ReferentieAanbieder>
        <jw315:Product>
          <ijw:Categorie>45</ijw:Categorie>
          <ijw:Code>YS1U</ijw:Code>
        </jw315:Product>
        <jw315:ToewijzingIngangsdatum>2021-01-01</jw315:ToewijzingIngangsdatum>
        <jw315:Omvang>
          <ijw:Volume>87</ijw:Volume>
          <ijw:Eenheid>83</ijw:Eenheid>
          <ijw:Frequentie>4</ijw:Frequentie>
        </jw315:Omvang>
        <jw315:Verwijzer>
          <ijw:Type>01</ijw:Type>
          <ijw:Naam>Utrecht</ijw:Naam>
        </jw315:Verwijzer>
        <jw315:Raamcontract>2</jw315:Raamcontract>
      </jw315:AangevraagdProduct>
      <jw315:AangevraagdProduct>
        <jw315:ReferentieAanbieder>88efe721359588</jw315:ReferentieAanbieder>
        <jw315:Product>
          <ijw:Categorie>52</ijw:Categorie>
        </jw315:Product>
        <jw315:ToewijzingIngangsdatum>2021-01-02</jw315:ToewijzingIngangsdatum>
        <jw315:Verwijzer>
          <ijw:Type>02</ijw:Type>
          <ijw:Naam>Utrecht</ijw:Naam>
        </jw315:Verwijzer>
        <jw315:Raamcontract>2</jw315:Raamcontract>
      </jw315:AangevraagdProduct>
    </jw315:AangevraagdeProducten>
  </jw315:Client>
</jw315:Bericht>`

If I create a naive_map from that, the result is:

`%{
  "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Bericht" => %{
    "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Client" => %{
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}AangevraagdeProducten" => %{
        "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}AangevraagdProduct" => [
          %{
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Omvang" => %{
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Eenheid" => "83",
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Frequentie" => "4",
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Volume" => "87"
            },
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Product" => %{
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Categorie" => "45",
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Code" => "YS1U"
            },
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Raamcontract" => "2",
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}ReferentieAanbieder" => "88efe721359587",
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}ToewijzingIngangsdatum" => "2021-01-01",
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Verwijzer" => %{
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Naam" => "Utrecht",
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Type" => "01"
            }
          },
          %{
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Product" => %{
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Categorie" => "52"
            },
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Raamcontract" => "2",
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}ReferentieAanbieder" => "88efe721359588",
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}ToewijzingIngangsdatum" => "2021-01-02",
            "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Verwijzer" => %{
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Naam" => "Utrecht",
              "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Type" => "02"
            }
          }
        ]
      },
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Bsn" => "999900006",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Geboortedatum" => %{
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Datum" => "2021-01-01"
      },
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Geslacht" => "1",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}GezagsdragerBekend" => "1",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Naam" => %{
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Geslachtsnaam" => %{
          "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Achternaam" => "Vries"
        },
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Voorletters" => "P"
      }
    },
    "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Header" => %{
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Afzender" => "22227338",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}BerichtCode" => "446",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}BerichtIdentificatie" => %{
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Dagtekening" => "2021-01-19",
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}Identificatie" => "MC008896A559"
      },
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}BerichtSubversie" => "0",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}BerichtVersie" => "3",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}Ontvanger" => "0344",
      "{http://www.istandaarden.nl/ijw/3_0/jw315/schema}XsdVersie" => %{
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}BasisschemaXsdVersie" => "1.2.0",
        "{http://www.istandaarden.nl/ijw/3_0/basisschema/schema}BerichtXsdVersie" => "1.0.2"
      }
    }
  }
}`

Instead of

`%{
  "jw315:Bericht" => %{
    "jw315:Client" => %{
      "jw315:AangevraagdeProducten" => %{
        "jw315:AangevraagdProduct" => [
          %{
            "jw315:Omvang" => %{
              "ijw:Eenheid" => "83",
              "ijw:Frequentie" => "4",
              "ijw:Volume" => "87"
            },
            "jw315:Product" => %{
              "ijw:Categorie" => "45",
              "ijw:Code" => "YS1U"
            },
            "jw315:Raamcontract" => "2",
            "jw315:ReferentieAanbieder" => "88efe721359587",
            "jw315:ToewijzingIngangsdatum" => "2021-01-01",
            "jw315:Verwijzer" => %{
              "ijw:Naam" => "Utrecht",
              "ijw:Type" => "01"
            }
          },
          %{
            "jw315:Product" => %{
              "ijw:Categorie" => "52"
            },
            "jw315:Raamcontract" => "2",
            "jw315:ReferentieAanbieder" => "88efe721359588",
            "jw315:ToewijzingIngangsdatum" => "2021-01-02",
            "jw315:Verwijzer" => %{
              "ijw:Naam" => "Utrecht",
              "ijw:Type" => "02"
            }
          }
        ]
      },
      "jw315:Bsn" => "999900006",
      "jw315:Geboortedatum" => %{
        "ijw:Datum" => "2021-01-01"
      },
      "jw315:Geslacht" => "1",
      "jw315:GezagsdragerBekend" => "1",
      "jw315:Naam" => %{
        "ijw:Geslachtsnaam" => %{
          "ijw:Achternaam" => "Vries"
        },
        "ijw:Voorletters" => "P"
      }
    },
    "jw315:Header" => %{
      "jw315:Afzender" => "22227338",
      "jw315:BerichtCode" => "446",
      "jw315:BerichtIdentificatie" => %{
        "ijw:Dagtekening" => "2021-01-19",
        "ijw:Identificatie" => "MC008896A559"
      },
      "jw315:BerichtSubversie" => "0",
      "jw315:BerichtVersie" => "3",
      "jw315:Ontvanger" => "0344",
      "jw315:XsdVersie" => %{
        "ijw:BasisschemaXsdVersie" => "1.2.0",
        "ijw:BerichtXsdVersie" => "1.0.2"
      }
    }
  }
}`

**Comment by homanchou** [comment]
Can you try removing the xmlns attributes from the root node and see what
happens?

**Comment by eddy147** [comment]
Yes, after removing the namespaces like this:
`Regex.replace(~r/(\sxmlns\:[\w\:="\/\.]+)+/, xml, "")`

The xml results in:

`%{
      "Bericht" => %{
        "Client" => %{
          "AangevraagdeProducten" => %{
            "AangevraagdProduct" => [
              %{
                "Omvang" => %{
                  "Eenheid" => "83",
                  "Frequentie" => "4",
                  "Volume" => "87"
                },
                "Product" => %{"Categorie" => "45", "Code" => "YS1U"},
                "Raamcontract" => "2",
                "ReferentieAanbieder" => "88efe721359587",
                "ToewijzingIngangsdatum" => "2021-01-01",
                "Verwijzer" => %{"Naam" => "Utrecht", "Type" => "01"}
              },
              %{
                "Product" => %{"Categorie" => "52"},
                "Raamcontract" => "2",
                "ReferentieAanbieder" => "88efe721359588",
                "ToewijzingIngangsdatum" => "2021-01-02",
                "Verwijzer" => %{"Naam" => "Utrecht", "Type" => "02"}
              }
            ]
          },
          "Bsn" => "999900006",
          "Geboortedatum" => %{"Datum" => "2021-01-01"},
          "Geslacht" => "1",
          "GezagsdragerBekend" => "1",
          "Naam" => %{
            "Geslachtsnaam" => %{"Achternaam" => "Vries"},
            "Voorletters" => "P"
          }
        },
        "Header" => %{
          "Afzender" => "22227338",
          "BerichtCode" => "446",
          "BerichtIdentificatie" => %{
            "Dagtekening" => "2021-01-19",
            "Identificatie" => "MC008896A559"
          },
          "BerichtSubversie" => "0",
          "BerichtVersie" => "3",
          "Ontvanger" => "0344",
          "XsdVersie" => %{
            "BasisschemaXsdVersie" => "1.2.0",
            "BerichtXsdVersie" => "1.0.2"
          }
        }
      }
    }`

However this Regex does not work for all cases.

It would be nice to have that as an option in naive_map()!

**Comment by jc00ke** [comment]
I'd love to see this as an option as well!

**Comment by homanchou** [comment]
merged fix
