### ISSUE TITLE
Minor patch breaks backwards compatibility

### ISSUE THREAD

**Issue by hazardfn** [homanchou/elixir-xml-to-map#6]
Hey!

Your latest version push broke backwards compatibility - we don't usually expect minor versions to do that and it caused a bit of an issue for us using it.

We have locked it back down to the 0.1.3 version for now, please keep the front-line engineers at the mercy of your tags in mind! 😃 

Thanks for building this useful library, we've got almost 3 years use out of it and this is my first issue 👍

**Comment by homanchou** [comment]
oh you are right!  Apologies.  I should have bumped it to version 1 then.  I will fix that, thanks!
